name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: short-sha  
      uses: benjlevesque/short-sha@v1.2
    - name: Build the Docker image
      run: docker build . -f Dockerfile -t argocd_demo:${{ steps.short-sha.outputs.sha }}
